// <auto-generated />
using System;
using Acropolis.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Acropolis.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ContentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc", "Id")
                        .IsDescending(true, false);

                    b.HasIndex("Action", "CreatedUtc", "Id")
                        .IsDescending(false, true, false);

                    b.HasIndex("ContentId", "CreatedUtc", "Id")
                        .IsDescending(false, true, false);

                    b.ToTable("Audit", "catalog");
                });

            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.EditorialContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CollectionKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CoverAsset")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<Guid[]>("ItemIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasDefaultValue(new Guid[0]);

                    b.Property<DateTimeOffset?>("PublishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(40)[]")
                        .HasDefaultValue(new string[0]);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("WorkText")
                        .HasMaxLength(500000)
                        .HasColumnType("character varying(500000)");

                    b.Property<string>("YouTubeId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Summary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Summary"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Summary"), new[] { "identity.gin_trgm_ops" });

                    b.HasIndex("Title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "identity.gin_trgm_ops" });

                    b.HasIndex("UpdatedUtc", "Id")
                        .IsDescending(true, false);

                    b.HasIndex("Status", "PublishedUtc", "Id")
                        .IsDescending(false, true, false);

                    b.HasIndex("Category", "Status", "PublishedUtc", "Id")
                        .IsDescending(false, false, true, false);

                    b.ToTable("Contents", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Contents_Category", "\"Category\" IN ('lecturas','documentales','videos','podcast','charlas-online','cursos')");

                            t.HasCheckConstraint("CK_Contents_Collection", "(\"CollectionKind\" IS NULL AND cardinality(\"ItemIds\")=0) OR (\"CollectionKind\" IS NOT NULL AND \"CollectionKind\" IN ('course','program') AND \"Category\"='cursos' AND \"WorkText\" IS NULL AND \"YouTubeId\" IS NULL)");

                            t.HasCheckConstraint("CK_Contents_CollectionSize", "array_position(\"ItemIds\", NULL) IS NULL AND cardinality(\"ItemIds\") BETWEEN 0 AND 100 AND (\"Status\" <> 'published' OR \"CollectionKind\" IS NULL OR cardinality(\"ItemIds\") > 0)");

                            t.HasCheckConstraint("CK_Contents_Cover", "\"CoverAsset\" IS NULL OR \"CoverAsset\" IN ('hero-acropolis','editorial-reading','editorial-podcast','editorial-dialogue','editorial-nature')");

                            t.HasCheckConstraint("CK_Contents_Duration", "\"DurationSeconds\" IS NULL OR \"DurationSeconds\" BETWEEN 1 AND 86400");

                            t.HasCheckConstraint("CK_Contents_Publication", "\"Status\" <> 'published' OR (\"PublishedUtc\" IS NOT NULL AND length(btrim(\"Summary\")) > 0 AND length(btrim(\"Body\")) > 0)");

                            t.HasCheckConstraint("CK_Contents_Slug", "length(\"Slug\") BETWEEN 2 AND 160 AND \"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_Contents_Status", "\"Status\" IN ('draft','published','archived')");

                            t.HasCheckConstraint("CK_Contents_Tags", "array_position(\"Tags\", NULL) IS NULL AND cardinality(\"Tags\") BETWEEN 0 AND 12");

                            t.HasCheckConstraint("CK_Contents_Title", "length(btrim(\"Title\")) BETWEEN 2 AND 180");

                            t.HasCheckConstraint("CK_Contents_WorkText", "\"WorkText\" IS NULL OR (\"Category\"='lecturas' AND length(btrim(\"WorkText\")) > 0 AND \"CollectionKind\" IS NULL)");

                            t.HasCheckConstraint("CK_Contents_YouTube", "\"YouTubeId\" IS NULL OR (\"YouTubeId\" ~ '^[A-Za-z0-9_-]{11}$' AND \"Category\" IN ('documentales','videos','podcast','charlas-online') AND \"CollectionKind\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.CatalogTopic", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(180).HasColumnType("character varying(180)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.Property<int>("Position").HasColumnType("integer");
                    b.Property<string>("Version").IsConcurrencyToken().IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<DateTimeOffset>("CreatedUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTimeOffset>("UpdatedUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.HasIndex("Name");
                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "identity.gin_trgm_ops" });
                    b.HasIndex("Position", "Id");
                    b.HasIndex("Status", "Position", "Id");
                    b.ToTable("Topics", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Topics_Slug", "length(\"Slug\") BETWEEN 2 AND 160 AND \"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");
                            t.HasCheckConstraint("CK_Topics_Name", "length(btrim(\"Name\")) BETWEEN 2 AND 180");
                            t.HasCheckConstraint("CK_Topics_Status", "\"Status\" IN ('active','archived')");
                            t.HasCheckConstraint("CK_Topics_Position", "\"Position\" >= 0");
                            t.HasCheckConstraint("CK_Topics_Version", "\"Version\" ~ '^[a-f0-9]{32}$'");
                        });
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ContentTopic", b =>
                {
                    b.Property<Guid>("ContentId").HasColumnType("uuid");
                    b.Property<Guid>("TopicId").HasColumnType("uuid");
                    b.HasKey("ContentId", "TopicId");
                    b.HasIndex("TopicId", "ContentId");
                    b.ToTable("ContentTopics", "catalog");
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.TopicDirectoryRevision", b =>
                {
                    b.Property<int>("Id").ValueGeneratedNever().HasColumnType("integer");
                    b.Property<string>("Version").IsConcurrencyToken().IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.HasKey("Id");
                    b.ToTable("TopicDirectory", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_TopicDirectory_Id", "\"Id\" = 1");
                            t.HasCheckConstraint("CK_TopicDirectory_Version", "\"Version\" ~ '^[a-f0-9]{32}$'");
                        });
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.TopicAudit", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("ActorId").HasColumnType("uuid");
                    b.Property<Guid>("TopicId").HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("Changes").IsRequired().HasMaxLength(1024).HasColumnType("character varying(1024)");
                    b.Property<DateTimeOffset>("CreatedUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("TopicId", "CreatedUtc", "Id").IsDescending(false, true, false);
                    b.ToTable("TopicAudit", "catalog");
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ContentTopic", b =>
                {
                    b.HasOne("Acropolis.Catalog.Infrastructure.EditorialContent", null).WithMany().HasForeignKey("ContentId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("Acropolis.Catalog.Infrastructure.CatalogTopic", null).WithMany().HasForeignKey("TopicId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ConsumptionSession", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthenticationBindingHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CategoryAtStart")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("CoverageIncomplete")
                        .HasColumnType("boolean");

                    b.Property<string>("CoverageJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("DurationChanged")
                        .HasColumnType("boolean");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<bool>("EndedReported")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastSequence")
                        .HasColumnType("integer");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");
                    b.HasIndex("AccountId","VisitId").IsUnique();
                    b.HasIndex("AccountId","StartedUtc","Id");
                    b.HasIndex("StartedUtc","Id");
                    b.HasIndex("ContentId","StartedUtc","Id");
                    b.ToTable("ConsumptionSessions", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ConsumptionSessions_Binding", "\"AuthenticationBindingHash\" ~ '^[a-f0-9]{64}$'");
                            t.HasCheckConstraint("CK_ConsumptionSessions_Version", "\"ContentVersion\" ~ '^[a-f0-9]{32}$'");
                            t.HasCheckConstraint("CK_ConsumptionSessions_Kind", "\"SourceKind\" IN ('reading','youtube')");
                            t.HasCheckConstraint("CK_ConsumptionSessions_Category", "\"CategoryAtStart\" IN ('lecturas','documentales','videos','podcast','charlas-online')");
                            t.HasCheckConstraint("CK_ConsumptionSessions_Sequence", "\"LastSequence\" BETWEEN 0 AND 1000000");
                            t.HasCheckConstraint("CK_ConsumptionSessions_Coverage", "jsonb_typeof(\"CoverageJson\")='array' AND jsonb_array_length(\"CoverageJson\")<=512");
                            t.HasCheckConstraint("CK_ConsumptionSessions_Duration", "\"DurationMs\" IS NULL OR \"DurationMs\" BETWEEN 1 AND 86400000");
                            t.HasCheckConstraint("CK_ConsumptionSessions_Time", "\"LastReceivedUtc\">=\"StartedUtc\"");
                        });
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ConsumptionPulse", b =>
                {
                    b.Property<string>("CanonicalHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("CoverageIncomplete")
                        .HasColumnType("boolean");

                    b.Property<int>("CreditedMs")
                        .HasColumnType("integer");

                    b.Property<bool>("EndedNow")
                        .HasColumnType("boolean");

                    b.Property<bool>("EndedReported")
                        .HasColumnType("boolean");

                    b.Property<int?>("ProgressBasisPoints")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId","Sequence");
                    b.HasIndex("ReceivedUtc","SessionId","Sequence");
                    b.ToTable("ConsumptionPulses", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ConsumptionPulses_Sequence", "\"Sequence\" BETWEEN 1 AND 1000000");
                            t.HasCheckConstraint("CK_ConsumptionPulses_Hash", "\"CanonicalHash\" ~ '^[a-f0-9]{64}$'");
                            t.HasCheckConstraint("CK_ConsumptionPulses_Credit", "\"CreditedMs\" BETWEEN 0 AND 15000");
                            t.HasCheckConstraint("CK_ConsumptionPulses_Progress", "\"ProgressBasisPoints\" IS NULL OR \"ProgressBasisPoints\" BETWEEN 0 AND 10000");
                            t.HasCheckConstraint("CK_ConsumptionPulses_End", "NOT \"EndedNow\" OR \"EndedReported\"");
                        });
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ConsumptionDaily", b =>
                {
                    b.Property<string>("CategoryAtStart")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("CreditedMs")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("DayUtc")
                        .HasColumnType("date");

                    b.Property<long>("EndedReports")
                        .HasColumnType("bigint");

                    b.Property<long>("KnownProgressSamples")
                        .HasColumnType("bigint");

                    b.Property<long>("ProgressBasisPointsSum")
                        .HasColumnType("bigint");

                    b.Property<long>("RecordedPulses")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("Starts")
                        .HasColumnType("bigint");

                    b.Property<long>("UnknownProgressSamples")
                        .HasColumnType("bigint");

                    b.HasKey("DayUtc","ContentId","ContentVersion","CategoryAtStart","SourceKind");
                    b.HasIndex("ContentId");
                    b.ToTable("ConsumptionDaily", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ConsumptionDaily_Version", "\"ContentVersion\" ~ '^[a-f0-9]{32}$'");
                            t.HasCheckConstraint("CK_ConsumptionDaily_Kind", "\"SourceKind\" IN ('reading','youtube')");
                            t.HasCheckConstraint("CK_ConsumptionDaily_Category", "\"CategoryAtStart\" IN ('lecturas','documentales','videos','podcast','charlas-online')");
                            t.HasCheckConstraint("CK_ConsumptionDaily_Counts", "\"Starts\">=0 AND \"RecordedPulses\">=0 AND \"CreditedMs\">=0 AND \"EndedReports\">=0 AND \"KnownProgressSamples\">=0 AND \"UnknownProgressSamples\">=0 AND \"ProgressBasisPointsSum\">=0 AND \"ProgressBasisPointsSum\"<=\"KnownProgressSamples\"::numeric*10000 AND \"KnownProgressSamples\"+\"UnknownProgressSamples\"=\"RecordedPulses\" AND \"EndedReports\"<=\"RecordedPulses\"");
                        });
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ConsumptionAccountDaily", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryAtStart")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("CreditedMs")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("DayUtc")
                        .HasColumnType("date");

                    b.Property<long>("EndedReports")
                        .HasColumnType("bigint");

                    b.Property<long>("KnownProgressSamples")
                        .HasColumnType("bigint");

                    b.Property<long>("ProgressBasisPointsSum")
                        .HasColumnType("bigint");

                    b.Property<long>("RecordedPulses")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("Starts")
                        .HasColumnType("bigint");

                    b.Property<long>("UnknownProgressSamples")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId","DayUtc","ContentId","ContentVersion","CategoryAtStart","SourceKind");
                    b.HasIndex("ContentId");
                    b.HasIndex("DayUtc","AccountId");
                    b.ToTable("ConsumptionAccountDaily", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_ConsumptionAccountDaily_Version", "\"ContentVersion\" ~ '^[a-f0-9]{32}$'");
                            t.HasCheckConstraint("CK_ConsumptionAccountDaily_Kind", "\"SourceKind\" IN ('reading','youtube')");
                            t.HasCheckConstraint("CK_ConsumptionAccountDaily_Category", "\"CategoryAtStart\" IN ('lecturas','documentales','videos','podcast','charlas-online')");
                            t.HasCheckConstraint("CK_ConsumptionAccountDaily_Counts", "\"Starts\">=0 AND \"RecordedPulses\">=0 AND \"CreditedMs\">=0 AND \"EndedReports\">=0 AND \"KnownProgressSamples\">=0 AND \"UnknownProgressSamples\">=0 AND \"ProgressBasisPointsSum\">=0 AND \"ProgressBasisPointsSum\"<=\"KnownProgressSamples\"::numeric*10000 AND \"KnownProgressSamples\"+\"UnknownProgressSamples\"=\"RecordedPulses\" AND \"EndedReports\"<=\"RecordedPulses\"");
                        });
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ConsumptionSession", b =>
                {
                    b.HasOne("Acropolis.Catalog.Infrastructure.EditorialContent", null).WithMany().HasForeignKey("ContentId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ConsumptionPulse", b =>
                {
                    b.HasOne("Acropolis.Catalog.Infrastructure.ConsumptionSession", null).WithMany().HasForeignKey("SessionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ConsumptionDaily", b =>
                {
                    b.HasOne("Acropolis.Catalog.Infrastructure.EditorialContent", null).WithMany().HasForeignKey("ContentId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });
            modelBuilder.Entity("Acropolis.Catalog.Infrastructure.ConsumptionAccountDaily", b =>
                {
                    b.HasOne("Acropolis.Catalog.Infrastructure.EditorialContent", null).WithMany().HasForeignKey("ContentId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
