// <auto-generated />
using System;
using Acropolis.Subscriptions.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Acropolis.Subscriptions.Infrastructure.Migrations
{
    [DbContext(typeof(SubscriptionsDbContext))]
    [Migration("20261007223000_AddSubscriptionNotifications")]
    partial class AddSubscriptionNotifications
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("subscriptions")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Acropolis.Subscriptions.Infrastructure.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActivatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NotificationTermGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UpdatedUtc", "Id");

                    b.HasIndex("Status", "UpdatedUtc", "Id");

                    b.HasIndex("Status", "ExpiresUtc", "Id");

                    b.ToTable("Subscriptions", "subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_Plan", "\"Plan\" IN ('free_beta','probationismo','annual')");

                            t.HasCheckConstraint("CK_Subscriptions_Terms", "(\"Plan\"='free_beta' AND \"ExpiresUtc\" IS NULL) OR (\"Plan\" IN ('probationismo','annual') AND \"ExpiresUtc\" IS NOT NULL AND \"ExpiresUtc\">\"StartsUtc\")");

                            t.HasCheckConstraint("CK_Subscriptions_Status", "\"Status\" IN ('active','cancelled','suspended')");
                        });
                });

            modelBuilder.Entity("Acropolis.Subscriptions.Infrastructure.SubscriptionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AfterExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AfterStartsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BeforeExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BeforeStartsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AfterPlan")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BeforePlan")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AfterStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("BeforeStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc", "Id");

                    b.HasIndex("SubscriptionId", "CreatedUtc");

                    b.HasIndex("UserId", "CreatedUtc");

                    b.ToTable("Audit", "subscriptions");
                });

            modelBuilder.Entity("Acropolis.Subscriptions.Infrastructure.SubscriptionNotification", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<int>("Attempts").HasColumnType("integer");
                    b.Property<DateTimeOffset>("CreatedUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("DeduplicationKey").IsRequired().HasMaxLength(96).HasColumnType("character varying(96)");
                    b.Property<DateTimeOffset?>("ExpiresUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Kind").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.Property<DateTimeOffset?>("LeaseExpiresUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("LeaseOwner").HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<DateTimeOffset>("NextAttemptUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Plan").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<Guid?>("SourceAuditId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("StartsUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Status").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.Property<Guid>("SubscriptionId").HasColumnType("uuid");
                    b.Property<Guid>("TermGeneration").HasColumnType("uuid");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("DeduplicationKey").IsUnique();
                    b.HasIndex("SourceAuditId").IsUnique();
                    b.HasIndex("Status", "NextAttemptUtc", "Id");
                    b.HasIndex("SubscriptionId", "Kind", "TermGeneration");
                    b.ToTable("NotificationOutbox", "subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_NotificationOutbox_Kind", "\"Kind\" IN ('assigned','renewed','expiring')");
                            t.HasCheckConstraint("CK_NotificationOutbox_Status", "\"Status\" IN ('pending','sending','sent','failed','cancelled')");
                            t.HasCheckConstraint("CK_NotificationOutbox_Attempts", "\"Attempts\" BETWEEN 0 AND 5");
                            t.HasCheckConstraint("CK_NotificationOutbox_Source", "(\"Kind\"='expiring' AND \"SourceAuditId\" IS NULL) OR (\"Kind\" IN ('assigned','renewed') AND \"SourceAuditId\" IS NOT NULL)");
                            t.HasCheckConstraint("CK_NotificationOutbox_Reminder", "\"Kind\"<>'expiring' OR \"ExpiresUtc\" IS NOT NULL");
                            t.HasCheckConstraint("CK_NotificationOutbox_Lease", "(\"Status\"='sending' AND \"LeaseOwner\" IS NOT NULL AND \"LeaseExpiresUtc\" IS NOT NULL) OR (\"Status\"<>'sending' AND \"LeaseOwner\" IS NULL AND \"LeaseExpiresUtc\" IS NULL)");
                            t.HasCheckConstraint("CK_NotificationOutbox_Terms", "(\"Plan\"='free_beta' AND \"ExpiresUtc\" IS NULL) OR (\"Plan\" IN ('probationismo','annual') AND \"ExpiresUtc\" IS NOT NULL AND \"ExpiresUtc\">\"StartsUtc\")");
                        });
                });

            modelBuilder.Entity("Acropolis.Subscriptions.Infrastructure.SubscriptionNotificationDeliveryState", b =>
                {
                    b.Property<int>("Id").HasColumnType("integer");
                    b.Property<DateTimeOffset>("NextSubmissionUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.ToTable("NotificationDeliveryState", "subscriptions", t => t.HasCheckConstraint("CK_NotificationDeliveryState_Id", "\"Id\"=1"));
                });

            modelBuilder.Entity("Acropolis.Subscriptions.Infrastructure.SubscriptionNotification", b =>
                {
                    b.HasOne("Acropolis.Subscriptions.Infrastructure.Subscription", null).WithMany().HasForeignKey("SubscriptionId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("Acropolis.Subscriptions.Infrastructure.SubscriptionAudit", null).WithMany().HasForeignKey("SourceAuditId").OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Acropolis.Subscriptions.Infrastructure.SubscriptionAudit", b =>
                {
                    b.HasOne("Acropolis.Subscriptions.Infrastructure.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
