<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Modules/Platform/Acropolis.Platform.Application/Acropolis.Platform.Application.csproj" />
    <ProjectReference Include="../Modules/Platform/Acropolis.Platform.Infrastructure/Acropolis.Platform.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
      <ProjectReference Include="../Modules/Identity/Acropolis.Identity.Application/Acropolis.Identity.Application.csproj" />
    <ProjectReference Include="../Modules/Identity/Acropolis.Identity.Infrastructure/Acropolis.Identity.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Catalog/Acropolis.Catalog.Application/Acropolis.Catalog.Application.csproj" />
    <ProjectReference Include="../Modules/Catalog/Acropolis.Catalog.Infrastructure/Acropolis.Catalog.Infrastructure.csproj" />
  </ItemGroup>
</Project>
