import { useEffect, useRef, useState } from 'react';
import { topics, topicMessage, type PublicTopic, type TopicPage } from '../../api/topics';
export function PublicTopicFilter({ value, change }: { value: string; change: (value: string) => void }) {
  const [open, setOpen] = useState(Boolean(value)); const [page, setPage] = useState(1); const [revision, setRevision] = useState(0); const [data, setData] = useState<TopicPage<PublicTopic> | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [retryShown, setRetryShown] = useState(false); const pending = useRef(false);
  useEffect(() => {
    if (!open) return; const controller = new AbortController(); pending.current = true; setLoading(true); setError('');
    void topics.publicList(page, controller.signal).then(result => { if (!controller.signal.aborted) { setData(result); pending.current = false; setLoading(false); } }, failure => { if (!controller.signal.aborted) { setError(topicMessage(failure)); setRetryShown(true); pending.current = false; setLoading(false); } });
    return () => controller.abort();
  }, [open, page, revision]);
  return <div className="public-topic-filter"><button className="link-button" type="button" aria-expanded={open} aria-controls="public-topic-options" onClick={() => setOpen(value => !value)}>Filtrar por tema</button>{open && <div id="public-topic-options" className="field" aria-busy={loading}><label htmlFor="public-topic-select">Tema</label><select id="public-topic-select" value={value} onChange={event => change(event.target.value)}><option value="">Todos los temas</option>{value && !data?.items.some(topic => topic.slug === value) && <option value={value}>{value}</option>}{data?.items.map(topic => <option key={topic.id} value={topic.slug}>{topic.name}</option>)}</select>{loading && <p role="status">Cargando temas…</p>}<div role={error ? 'alert' : undefined}>{error && <p>{error}</p>}{retryShown && <button type="button" className="link-button" aria-disabled={loading} onClick={() => { if (!pending.current) { pending.current = true; setRevision(value => value + 1); } }}>{loading ? 'Cargando temas…' : error ? 'Reintentar temas' : 'Actualizar temas públicos'}</button>}</div>{data && data.total > 100 && <div className="topic-actions"><button className="link-button" type="button" disabled={page <= 1 || loading} onClick={() => setPage(value => value - 1)}>Temas anteriores</button><span>Página {page}</span><button className="link-button" type="button" disabled={page * data.pageSize >= data.total || loading} onClick={() => setPage(value => value + 1)}>Más temas</button></div>}{data?.total === 0 && <p>No hay temas disponibles. Puedes seguir buscando por formato o texto.</p>}</div>}</div>;
}
